  
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:dbname=qdpm_z800;host=192.168.10.234'
      profiler: false
      username: root
      password: "<?php echo urlencode('adoojena') ; ?>"
      attributes:
        quote_identifier: true  
  