<?php

/**
 * DriveTracker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Luke Foster
 * @version    SVN: $Id
 */
class DriveTrackers extends BaseDriveTrackers
{
    public static function getSchema()
    {
        $drives =  Doctrine_Core::getTable('DriveTrackers')->createQuery('d')        
            ->orderBy('d.id')
            ->fetchArray();
        
        $schema = array();

        foreach($drives as $d)
        {
            $schema[$d['id']] = $d['name'];
        }
        
        return $schema;
    }

    public static function getNextDriveInt()
    {
        $getNext =  Doctrine_Core::getTable('DriveTrackers')->createQuery()        
                        ->select('MAX(name) AS new_name')
                        ->fetchArray();

        $getNextInt = $getNext[0]['new_name']+1;
    
        return $getNextInt;
    }

    public static function getNextDriveName()
    {
        $getNext =  Doctrine_Core::getTable('DriveTrackers')->createQuery()        
                        ->select('MAX(name) AS new_name')
                        ->fetchArray();
                        
        $getNextInt = $getNext[0]['new_name']+1;
        $str = 'X' . sprintf('%05d', $getNextInt);
    
        return $str;
    }

}