<?php

/**
 * DriveTrackerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DriveTrackerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DriveTrackerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DriveTracker');
    }
}