<?php

/**
 * DriveTracker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DriveTrackers extends BaseDriveTrackers
{
    public static function getSchema()
        {
        $drives =  Doctrine_Core::getTable('DriveTrackers')->createQuery('d')        
            ->orderBy('d.id')
            ->fetchArray();
        
        $schema = array();

        foreach($drives as $d)
        {
            $schema[$d['id']] = $d['name'];
        }
        
        return $schema;

    }

}
