<?php

/**
 * ProjectDriveTrackersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectDriveTrackersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectDriveTrackersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('project_drive_trackers');
    }
}
