<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/08/07 10:56:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm_z800;host=192.168.10.234',
  'profiler' => false,
  'username' => 'root',
  'password' => 'adoojena',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
