<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/07/23 13:57:45
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'reports_access_projects',
  ),
  'view' => 
  array (
    'credentials' => 
    array (
    ),
  ),
);
