<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/07/23 13:58:06
sfConfig::add(array(
  'mod_discussionsreports_enabled' => true,
  'mod_discussionsreports_view_class' => 'sfPHP',
));
