<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/07/22 09:22:38
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
