<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/08/13 15:34:41
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
