<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/07/23 13:57:45
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
