<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/07/22 11:06:49
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
