<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/08/07 13:18:18
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
