<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/07/23 06:09:48
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
