<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/07/22 10:58:28
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
