<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/08/15 10:58:36
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
