<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProjectDriveTrackers', 'doctrine');

/**
 * BaseProjectDriveTrackers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $project_id
 * @property integer $drive_tracker_id
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method integer     getProjectId()        Returns the current record's "project_id" value
 * @method integer     getDriveTrackerId()   Returns the current record's "drive_tracker_id" value
 * @package    sf_sandbox
 * @subpackage model
 * @author     Luke Foster
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class ProjectBaseDriveTrackers sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_drive_trackers');
        $this->hasColumn('id', 'integer', 4, array(
               'type' => 'integer',
               'fixed' => 0,
               'unsigned' => false,
               'primary' => true,
               'autoincrement' => true,
               'length' => 4,
          ));
        $this->hasColumn('project_id', 'integer', 4, array(
               'type' => 'integer',
               'fixed' => 0,
               'unsigned' => false,
               'primary' => false,
               'notnull' => true,
               'autoincrement' => false,
               'length' => 4,
          ));
        $this->hasColumn('drive_tracker_id', 'integer', 4, array(
               'type' => 'integer',
               'fixed' => 0,
               'unsigned' => false,
               'primary' => false,
               'notnull' => true,
               'autoincrement' => false,
               'length' => 4,
          ));
    }

    public function setUp()
    {
        parent::setUp();
    }
}